package:
  name: protocaller
  version: 1.2.0

source:
  path: ../

build:
  noarch: python
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  script:
    - mkdir -p $PREFIX/site-packages
    - cp -r $RECIPE_DIR/../ProtoCaller $PREFIX/site-packages/ProtoCaller

requirements:
  build:
    - python>=3.7
    - numpy
  run:
    - python>=3.7
    - ambertools
    - beautifulsoup4
    - biopython
    - biosimspace
    - geckodriver
    - libcblas
    - libnetcdf
    - mdanalysis
    - numpy
    - openbabel=2.4.1
    - parmed
    - pdb2pqr
    - pdbfixer
    - pygtail
    - pymbar
    - rdkit
    - requests
    - selenium
    - selenium-requests
    - sire

test:
  requires:
    - pytest

about:
  home: https://github.com/protocaller/protocaller
  summary: Full automation of high-throughput relative binding free energy simulations.
  license: GPL-3.0
  license_file: LICENSE
